---
---
/* essays-data.js — generated by Jekyll from post front matter */
{% assign all_essays = site.posts | sort: "date" | reverse %}
var ALL_ESSAYS = [{% for essay in all_essays %}
{% assign essay_img = essay.thumb | default: essay.image | default: "" %}
{% if essay.story_card and essay.excerpt %}{% assign essay_card_excerpt = essay.excerpt | strip_html | normalize_whitespace | truncatewords: 24 %}{% else %}{% assign essay_card_excerpt = essay.content | strip_html | normalize_whitespace | truncatewords: 24 %}{% endif %}
  {href:{{ essay.url | split: "/" | last | jsonify }},title:{{ essay.title | jsonify }},subtitle:{{ essay.subtitle | default: "" | jsonify }},img:{% if essay_img contains '://' %}{{ essay_img | jsonify }}{% elsif essay_img != "" %}{{ essay_img | absolute_url | jsonify }}{% else %}""{% endif %},date:'{{ essay.date | date: "%b %-d, %Y" }}',excerpt:{{ essay_card_excerpt | default: "" | jsonify }},series:{{ essay.series | default: "" | jsonify }},seriesOrder:{{ essay.series_order | default: 0 }},coverStyle:{{ essay.cover_style | default: "" | jsonify }},coverLabel:{{ essay.cover_label | default: "" | jsonify }},story:{% if essay.story_card %}true{% else %}false{% endif %},storyUrl:{{ essay.story_url | default: "" | jsonify }}}{% unless forloop.last %},{% endunless %}{% endfor %}
];
