---
---
/* essays-data.js—Generated by Jekyll from _posts front matter */
var ALL_ESSAYS = [{% for post in site.posts %}
  {href:'{{ post.slug }}.html',title:{{ post.title | jsonify }},subtitle:{{ post.subtitle | jsonify }},img:{% if post.thumb contains '://' %}{{ post.thumb | jsonify }}{% else %}{{ post.thumb | absolute_url | jsonify }}{% endif %},date:'{{ post.date | date: "%b %-d, %Y" }}',readTime:'{{ post.read_time }}',series:{{ post.series | jsonify }},seriesOrder:{{ post.series_order | default: 0 }}}{% unless forloop.last %},{% endunless %}{% endfor %}
];
