---
---
/* essays-data.js—Generated by Jekyll from _posts front matter */
{% assign all_essays = site.posts | sort: "date" | reverse %}
var ALL_ESSAYS = [{% for essay in all_essays %}
  {href:'{{ essay.url | split: "/" | last }}',title:{{ essay.title | jsonify }},subtitle:{{ essay.subtitle | jsonify }},img:{% assign essay_img = essay.thumb | default: essay.image | default: "" %}{% if essay_img contains '://' %}{{ essay_img | jsonify }}{% elsif essay_img != "" %}{{ essay_img | absolute_url | jsonify }}{% else %}""{% endif %},date:'{{ essay.date | date: "%b %-d, %Y" }}',readTime:'{{ essay.read_time }}',series:{{ essay.series | jsonify }},seriesOrder:{{ essay.series_order | default: 0 }}}{% unless forloop.last %},{% endunless %}{% endfor %}
];