/* fragments-nav.js—Replaces .fragments-nav with The Fragments thumbnail cards */
(function () {
  'use strict';

  var nav = document.querySelector('.fragments-nav');
  if (!nav) return;

  /* Build fragments list from ALL_ESSAYS (generated by Jekyll) */
  if (typeof ALL_ESSAYS === 'undefined') return;
  var FRAGMENTS = ALL_ESSAYS.filter(function (e) {
    return e.series === 'fragments';
  }).sort(function (a, b) {
    return (a.seriesOrder || 0) - (b.seriesOrder || 0);
  });

  var current = window.location.pathname.split('/').pop() || '';

  /* Title with split colors */
  var html = '<p class="series-nav-title">'
    + '<span class="series-nav-title-on">The Fragments</span>'
    + '<span class="series-nav-title-sub"> \u00b7 A personal essay and three short stories\u2014memory, interference, and the decisions we make on behalf of others</span>'
    + '</p>';

  /* Thumbnail cards row */
  html += '<div class="series-nav-cards">';

  FRAGMENTS.forEach(function (f, i) {
    var isCurrent = (f.href === current);
    var img = f.img || '';
    var label = f.title.replace(/"/g, '&quot;');

    var inner = '<div class="series-thumb-card' + (isCurrent ? ' series-thumb-card--current' : '') + '">'
      + (img ? '<img src="' + img + '" alt="' + label + '" loading="lazy">' : '<div class="series-thumb-img-placeholder"></div>')
      + '<span class="series-thumb-label">'
      + '<span class="series-thumb-num">' + (i + 1) + '</span>. ' + f.title
      + '</span>'
      + '</div>';

    if (isCurrent) {
      html += inner;
    } else {
      html += '<a href="' + f.href + '" class="series-thumb-link" aria-label="' + label + '">' + inner + '</a>';
    }
  });

  html += '</div>';

  nav.innerHTML = html;
})();
