/* series-nav.js—Replaces .series-nav with On Series thumbnail cards */
(function () {
  'use strict';

  var nav = document.querySelector('.series-nav');
  if (!nav) return;

  /* Build series from ALL_ESSAYS (generated by Jekyll) */
  if (typeof ALL_ESSAYS === 'undefined') return;
  var SERIES = ALL_ESSAYS.filter(function (e) {
    return e.series === 'on-series';
  }).sort(function (a, b) {
    return (a.seriesOrder || 0) - (b.seriesOrder || 0);
  });

  var current = window.location.pathname.split('/').pop() || '';

  /* Title with split colors */
  var html = '<p class="series-nav-title">'
    + '<span class="series-nav-title-on">The On Series</span>'
    + '<span class="series-nav-title-sub"> \u00b7 Essays on what we build inside ourselves\u2014and why</span>'
    + '</p>';

  /* Thumbnail cards row */
  html += '<div class="series-nav-cards">';

  SERIES.forEach(function (s, i) {
    var isCurrent = (s.href === current);
    var img = s.img || '';
    var label = s.title.replace(/"/g, '&quot;');

    var inner = '<div class="series-thumb-card' + (isCurrent ? ' series-thumb-card--current' : '') + '">'
      + (img ? '<img src="' + img + '" alt="' + label + '" loading="lazy">' : '<div class="series-thumb-img-placeholder"></div>')
      + '<span class="series-thumb-label">'
      + '<span class="series-thumb-num">' + (i + 1) + '</span>. ' + s.title
      + '</span>'
      + '</div>';

    if (isCurrent) {
      html += inner;
    } else {
      html += '<a href="' + s.href + '" class="series-thumb-link" aria-label="' + label + '">' + inner + '</a>';
    }
  });

  html += '</div>';

  nav.innerHTML = html;
})();
