---
---
/* Offline shell for the tools. Each instrument runs entirely in the
   browser, so a cached copy IS the whole tool: once a page has been
   visited, it opens without a connection.

   Everything here is served stale-while-revalidate — instant from cache,
   refreshed in the background on every online visit. TOOL_PAGES is
   generated by Jekyll from _data/tools.yml; adding an instrument to the
   catalogue adds it here. The worker is registered only from the tool
   pages, but once it is active it covers the origin, so TOOL_ASSETS is
   served from cache on every page of the site, not only on those.

   WHEN TO BUMP CACHE. Not for a tool page changing: those pages are
   self-contained, and one stale load of an instrument is the same
   instrument. Bump it when the caching scheme itself changes, or when
   the asset list does. v23 is the first: keys now carry ?v=.

   WHAT A BUMP DOES NOT DO. It does not spare the first load after a
   deploy. The new worker has to be fetched, installed and activated
   before it can serve anything, and the navigation that fetches it is
   still answered by the old one. Measured: with only a version bump, the
   first load after a deploy is stale either way; it is the ?v= keying
   below that makes it fresh, and only from the release after the one
   that introduces it. Nothing here can reach a worker already installed
   on a reader's machine — that copy self-heals on its second load. */
"use strict";

var CACHE = "olae-tools-v23";

var TOOL_PAGES = [
  "/tools/",   /* the catalogue itself, so "all of them" works offline */
  {% for tool in site.data.tools %}"/{{ tool.slug }}/"{% unless forloop.last %}, {% endunless %}{% endfor %}
];

var TOOL_ASSETS = [
  "/css/style.css",   /* the catalogue page's stylesheet */
  "/css/fonts.css",
  "/css/palettes.css",   /* the /themes/ wardrobe; the catalogue shell links it */
  /* /tools/ uses the site's default shell; keep its navigation and theme
     controls functional offline as well as its content and styles. */
  "/js/site-nav.js",
  "/js/palettes.js",
  "/js/theme.js",
  "/js/divider-lines.js",
  "/js/header-autohide.js",
  "/js/rain-engine.js",
  "/js/astronomy.js",
  "/fonts/cormorant-garamond-italic-latin-ext.woff2",
  "/fonts/cormorant-garamond-italic-latin.woff2",
  "/fonts/cormorant-garamond-latin-ext.woff2",
  "/fonts/cormorant-garamond-latin.woff2",
  "/fonts/eb-garamond-italic-latin-ext.woff2",
  "/fonts/eb-garamond-italic-latin.woff2",
  "/fonts/eb-garamond-latin-ext.woff2",
  "/fonts/eb-garamond-latin.woff2"
];

var PRECACHE = TOOL_PAGES.concat(TOOL_ASSETS);

self.addEventListener("install", function(e){
  e.waitUntil(
    caches.open(CACHE)
      .then(function(c){ return c.addAll(PRECACHE); })
      .then(function(){ return self.skipWaiting(); })
  );
});

self.addEventListener("activate", function(e){
  e.waitUntil(
    caches.keys().then(function(keys){
      /* only retire our own old versions — a future site-level cache
         under another prefix must survive this worker's activation */
      return Promise.all(keys.filter(function(k){ return k.indexOf("olae-tools-") === 0 && k !== CACHE; })
                             .map(function(k){ return caches.delete(k); }));
    }).then(function(){ return self.clients.claim(); })
  );
});

self.addEventListener("fetch", function(e){
  if(e.request.method !== "GET") return;
  var url = new URL(e.request.url);
  if(url.origin !== self.location.origin) return;
  if(PRECACHE.indexOf(url.pathname) === -1) return;

  /* The key carries ?v= when the request has one. Keying on the bare
     pathname threw the site's own cache-busting away: head.html stamps
     ?v=… on the shared CSS and JS precisely so a release can invalidate
     them, and this worker answered the new URL with yesterday's file. A
     reader with it installed therefore got new markup over an old
     stylesheet for one load after every deploy — which is how a slate
     page ended up under an ash header the day Follow the sky shipped.
     Anything unversioned (a tool page, /js/astronomy.js?until=…) keys on
     the pathname exactly as before. */
  var key = url.searchParams.has("v")
    ? url.pathname + "?v=" + url.searchParams.get("v")
    : url.pathname;

  e.respondWith(
    caches.open(CACHE).then(function(c){
      return c.match(key).then(function(hit){
        var refresh = fetch(e.request).then(function(res){
          if(res && res.ok) c.put(key, res.clone());
          return res;
        /* Offline and this version was never cached: the copy from the
           install, under the bare pathname, is the honest fallback. */
        }).catch(function(){ return hit || c.match(url.pathname); });
        return hit || refresh;
      });
    })
  );
});
