---
---
/* Offline shell for the tools. Each instrument runs entirely in the
   browser, so a cached copy IS the whole tool: once a page has been
   visited, it opens without a connection. Tool pages are served
   stale-while-revalidate — instant from cache, refreshed in the
   background on every online visit — so a change to a tool needs no
   version bump here; bump CACHE only if the asset list itself changes.
   TOOL_PAGES is generated by Jekyll from _data/tools.yml — adding an
   instrument to the catalogue adds it here; still bump CACHE when the
   list changes. Registered only from the tool pages; every other URL
   on the site is left to the network untouched. */
"use strict";

var CACHE = "olae-tools-v7";

var TOOL_PAGES = [
  "/tools/",   /* the catalogue itself, so "all of them" works offline */
  {% for tool in site.data.tools %}"/{{ tool.slug }}/"{% unless forloop.last %}, {% endunless %}{% endfor %}
];

var TOOL_ASSETS = [
  "/css/style.css",   /* the catalogue page's stylesheet */
  "/css/fonts.css",
  /* /tools/ uses the site's default shell; keep its navigation and theme
     controls functional offline as well as its content and styles. */
  "/js/site-nav.js",
  "/js/theme.js",
  "/js/divider-lines.js",
  "/js/header-autohide.js",
  "/js/rain-engine.js",
  "/js/astronomy.js",
  "/fonts/cormorant-garamond-italic-latin-ext.woff2",
  "/fonts/cormorant-garamond-italic-latin.woff2",
  "/fonts/cormorant-garamond-latin-ext.woff2",
  "/fonts/cormorant-garamond-latin.woff2",
  "/fonts/eb-garamond-italic-latin-ext.woff2",
  "/fonts/eb-garamond-italic-latin.woff2",
  "/fonts/eb-garamond-latin-ext.woff2",
  "/fonts/eb-garamond-latin.woff2"
];

var PRECACHE = TOOL_PAGES.concat(TOOL_ASSETS);

self.addEventListener("install", function(e){
  e.waitUntil(
    caches.open(CACHE)
      .then(function(c){ return c.addAll(PRECACHE); })
      .then(function(){ return self.skipWaiting(); })
  );
});

self.addEventListener("activate", function(e){
  e.waitUntil(
    caches.keys().then(function(keys){
      /* only retire our own old versions — a future site-level cache
         under another prefix must survive this worker's activation */
      return Promise.all(keys.filter(function(k){ return k.indexOf("olae-tools-") === 0 && k !== CACHE; })
                             .map(function(k){ return caches.delete(k); }));
    }).then(function(){ return self.clients.claim(); })
  );
});

self.addEventListener("fetch", function(e){
  if(e.request.method !== "GET") return;
  var url = new URL(e.request.url);
  if(url.origin !== self.location.origin) return;
  if(PRECACHE.indexOf(url.pathname) === -1) return;

  /* cache keys are bare pathnames, so ?v=… and ?until=… hit the same entry */
  e.respondWith(
    caches.open(CACHE).then(function(c){
      return c.match(url.pathname).then(function(hit){
        var refresh = fetch(e.request).then(function(res){
          if(res && res.ok) c.put(url.pathname, res.clone());
          return res;
        }).catch(function(){ return hit; });
        return hit || refresh;
      });
    })
  );
});
