---
---
/* Offline shell for the tools. Each instrument runs entirely in the
   browser, so a cached copy IS the whole tool: once a page has been
   visited, it opens without a connection.

   Everything here is served stale-while-revalidate — instant from cache,
   refreshed in the background on every online visit. TOOL_PAGES is
   generated by Jekyll from _data/tools.yml; adding an instrument to the
   catalogue adds it here. The worker is registered only from the tool
   pages, but once it is active it covers the origin, so TOOL_ASSETS is
   served from cache on every page of the site, not only on those.

   NOT EVERYTHING IS PRECACHED. PDFJS_ROOT below is cached on use instead:
   the bundled reader is 7.3 MB, and install's addAll is all-or-nothing and
   blocking, so precaching it would make every reader who never opens a PDF
   pay for one — on a phone, before the worker installs at all. Cached on
   first use, it costs only the readers who use it, and costs them nothing
   the second time. Same shelf, same stale-while-revalidate, different moment.

   WHEN TO BUMP CACHE. Not for a tool page changing: those pages are
   self-contained, and one stale load of an instrument is the same
   instrument. Bump it when the caching scheme itself changes, or when
   the asset list does. v23 is the first: keys now carry ?v=.

   WHAT A BUMP DOES NOT DO. It does not spare the first load after a
   deploy. The new worker has to be fetched, installed and activated
   before it can serve anything, and the navigation that fetches it is
   still answered by the old one. Measured: with only a version bump, the
   first load after a deploy is stale either way; it is the ?v= keying
   below that makes it fresh, and only from the release after the one
   that introduces it. Nothing here can reach a worker already installed
   on a reader's machine — that copy self-heals on its second load. */
"use strict";

var CACHE = "olae-tools-v36";

/* Reader-selected copies survive every replacement of the tool shell. */
var READING_PAGES = 'olae-reading-pages-v1';
var READING_ASSETS = 'olae-reading-assets-v1';
var ESSAY_PAGES = [
  {% for post in site.posts %}{% unless post.series == "story" %}{ url: {{ post.url | jsonify }}, title: {{ post.title | jsonify }} },{% endunless %}{% endfor %}
];

var TOOL_PAGES = [
  "/tools/",   /* the catalogue itself, so "all of them" works offline */
  "/offline/", /* the reader's saved shelf and navigation fallback */
  {% for tool in site.data.tools %}"/{{ tool.slug }}/"{% unless forloop.last %}, {% endunless %}{% endfor %}
];

var TOOL_ASSETS = [
  "/css/desk.css",
  "/js/desk.js",
  "/js/vendor/marked-18.0.11.umd.js",
  "/js/reader-markdown.js",
  "/js/reader-pdf.js",
  "/css/reader-pdf.css",
  "/js/reader-clear.js",
  "/js/list-lots-clear.js",
  "/js/list-trim.js",
  "/js/text-tool-clear.js",
  "/css/style.css",   /* the catalogue page's stylesheet */
  "/css/fonts.css",
  "/css/reading.css",
  "/js/reading-settings.js",
  "/js/reading-listen.js",
  "/js/reading-offline.js",
  "/css/palettes.css",   /* the /themes/ wardrobe; the catalogue shell links it */
  "/css/search.css",   /* the drawer's and the strip's search fields, which every shell carries */
  /* /tools/ uses the site's default shell; keep its navigation and theme
     controls functional offline as well as its content and styles. */
  "/js/site-nav.js",
  "/js/let-it-snow.js",
  "/css/let-it-snow.css",
  "/js/palettes.js",
  "/js/theme.js",
  "/js/divider-lines.js",
  "/js/header-autohide.js",
  "/js/rain-engine.js",
  "/js/astronomy.js",
  "/css/window-sky.css",
  "/js/sky-instruments.js",
  "/js/bright-stars.js",
  "/js/sky-map.js",
  "/js/vendor/astronomy-engine-2.1.19.min.js",
  "/fonts/cormorant-garamond-italic-latin-ext.woff2",
  "/fonts/cormorant-garamond-italic-latin.woff2",
  "/fonts/cormorant-garamond-latin-ext.woff2",
  "/fonts/cormorant-garamond-latin.woff2",
  "/fonts/eb-garamond-italic-latin-ext.woff2",
  "/fonts/eb-garamond-italic-latin.woff2",
  "/fonts/eb-garamond-latin-ext.woff2",
  "/fonts/eb-garamond-latin.woff2"
];

var PRECACHE = TOOL_PAGES.concat(TOOL_ASSETS);

/* Everything under here is the bundled PDF.js: hundreds of files, most of
   which a given document never asks for. Kept out of PRECACHE, kept on the
   same shelf once fetched. */
var PDFJS_ROOT = "/js/vendor/pdfjs/";

function resourceKey(url) {
  return url.searchParams.has('v') ? url.pathname + '?v=' + url.searchParams.get('v') : url.pathname;
}
function readingResource(url) {
  return url.origin === self.location.origin &&
    (/^\/(css|js|fonts|images)\//.test(url.pathname) && url.pathname.indexOf(PDFJS_ROOT) !== 0 && url.pathname !== PDFJS_ROOT.slice(0, -1) ||
     /^\/(manifest\.json|favicon[^/]*|apple-touch-icon[^/]*|on-icon[^/]*)$/.test(url.pathname));
}
async function savedPieces() {
  var cache = await caches.open(READING_PAGES);
  var keys = await cache.keys();
  return Promise.all(keys.map(async function (request) {
    var url = new URL(request.url);
    var response = await cache.match(request);
    var known = ESSAY_PAGES.find(function (piece) { return piece.url === url.pathname; });
    var title = known ? known.title : 'Saved piece';
    try { title = decodeURIComponent(response.headers.get('X-Reading-Title') || '') || title; } catch (e) {}
    return { url: url.pathname, title: title };
  }));
}
var readingQueue = Promise.resolve();
self.addEventListener('message', function (e) {
  var data = e.data;
  var port = e.ports && e.ports[0];
  if (!port || !data || ['LIST_READING', 'SAVE_READING', 'REMOVE_READING'].indexOf(data.type) < 0) return;
  readingQueue = readingQueue.catch(function () {}).then(async function () {
    if (data.type !== 'LIST_READING') {
      var url = new URL(data.url, self.location.origin);
      if (url.origin !== self.location.origin || url.search || url.hash) throw new Error('invalid page');
      var pages = await caches.open(READING_PAGES);
      if (data.type === 'REMOVE_READING') {
        await pages.delete(url.pathname);
        if (!(await pages.keys()).length) await caches.delete(READING_ASSETS);
      } else {
        var piece = ESSAY_PAGES.find(function (p) { return p.url === url.pathname; });
        if (!piece || !Array.isArray(data.resources) || data.resources.length > 100) throw new Error('invalid page');
        var resources = Array.from(new Set(data.resources.map(function (raw) {
          var asset = new URL(raw, self.location.origin);
          if (!readingResource(asset)) throw new Error('invalid resource');
          return resourceKey(asset);
        })));
        var response = await fetch(url.pathname, { cache: 'reload' });
        if (!response.ok || !(response.headers.get('Content-Type') || '').includes('text/html')) throw new Error('page unavailable');
        var assets = await caches.open(READING_ASSETS);
        await Promise.all(resources.map(async function (key) {
          var asset = await fetch(key, { cache: 'reload' });
          if (!asset.ok) throw new Error('asset unavailable');
          await assets.put(key, asset);
        }));
        var headers = new Headers(response.headers);
        headers.set('X-Reading-Title', encodeURIComponent(piece.title));
        await pages.put(url.pathname, new Response(response.body, { status: response.status, statusText: response.statusText, headers: headers }));
      }
    }
    port.postMessage({ ok: true, pieces: await savedPieces() });
  });
  e.waitUntil(readingQueue.catch(function () { port.postMessage({ ok: false }); }));
});

self.addEventListener("install", function(e){
  e.waitUntil(
    caches.open(CACHE)
      .then(function(c){ return c.addAll(PRECACHE); })
      .then(function(){ return self.skipWaiting(); })
  );
});

self.addEventListener("activate", function(e){
  e.waitUntil(
    caches.keys().then(function(keys){
      /* only retire our own old versions — a future site-level cache
         under another prefix must survive this worker's activation */
      return Promise.all(keys.filter(function(k){ return k.indexOf("olae-tools-") === 0 && k !== CACHE; })
                             .map(function(k){ return caches.delete(k); }));
    }).then(function(){ return self.clients.claim(); })
  );
});

self.addEventListener("fetch", function(e){
  if(e.request.method !== "GET") return;
  var url = new URL(e.request.url);
  if(url.origin !== self.location.origin) return;
  var onUse = url.pathname.lastIndexOf(PDFJS_ROOT, 0) === 0;
  var isTool = PRECACHE.indexOf(url.pathname) !== -1;
  if (!onUse && !isTool && (e.request.mode === 'navigate' || ESSAY_PAGES.some(function (piece) { return piece.url === url.pathname; }))) {
    /* A visit does not write a page. The chosen offline copy is a snapshot. */
    e.respondWith(fetch(e.request).catch(async function () {
      var pages = await caches.open(READING_PAGES);
      return await pages.match(url.pathname) || await (await caches.open(CACHE)).match('/offline/') || Response.error();
    }));
    return;
  }
  if (!onUse && !isTool) {
    if (readingResource(url)) {
      e.respondWith(fetch(e.request).catch(async function () {
        return await (await caches.open(READING_ASSETS)).match(resourceKey(url)) || Response.error();
      }));
    }
    return;
  }

  /* The key carries ?v= when the request has one. Keying on the bare
     pathname threw the site's own cache-busting away: head.html stamps
     ?v=… on the shared CSS and JS precisely so a release can invalidate
     them, and this worker answered the new URL with yesterday's file. A
     reader with it installed therefore got new markup over an old
     stylesheet for one load after every deploy — which is how a slate
     page ended up under an ash header the day Follow the sky shipped.
     Anything unversioned (a tool page, /js/astronomy.js?until=…) keys on
     the pathname exactly as before. */
  var key = url.searchParams.has("v")
    ? url.pathname + "?v=" + url.searchParams.get("v")
    : url.pathname;

  e.respondWith(
    caches.open(CACHE).then(function(c){
      return c.match(key).then(function(hit){
        var refresh = fetch(e.request).then(function(res){
          if(res && res.ok) c.put(key, res.clone());
          return res;
        /* Offline and this version was never cached: the copy from the
           install, under the bare pathname, is the honest fallback. */
        }).catch(async function(){
          return hit || await (await caches.open(READING_ASSETS)).match(key) || c.match(url.pathname);
        });
        return hit || refresh;
      });
    })
  );
});
